INSERT INTO genre VALUES(1, 'thriller');
INSERT INTO genre VALUES(2, 'comédie');
INSERT INTO genre VALUES(3, 'drame');
INSERT INTO genre VALUES(4, 'policier');
INSERT INTO genre VALUES(5, 'aventure');
INSERT INTO genre VALUES(6, 'horreur');
INSERT INTO acteur VALUES(3, 'Penn', 'Sean', 'Etats-Unis');
INSERT INTO acteur VALUES(5, 'Canet', 'Guillaume', 'France');
INSERT INTO acteur VALUES(6, 'Cotillard', 'Marion', 'France');
INSERT INTO acteur VALUES(7, 'Di Caprio', 'Leonardo', 'Etats-Unis');
INSERT INTO acteur VALUES(8, 'Dujardin', 'Jean', 'France');
INSERT INTO acteur VALUES(9, 'Boon', 'Dany', 'France');
INSERT INTO acteur VALUES(10, 'Tautou', 'Audrey', 'France');
INSERT INTO acteur VALUES(11, 'Cornillac', 'Clovis', 'France');
INSERT INTO acteur VALUES(13, 'Eastwood', 'Clint', 'Etats-Unis');
INSERT INTO acteur VALUES(15, 'Depp', 'Johnny', 'Etats-Unis');
INSERT INTO acteur VALUES(17, 'Dupontel', 'Albert', 'France');
INSERT INTO acteur VALUES(18, 'Cassel', 'Vincent', 'France');
INSERT INTO acteur VALUES(19, 'Cassel', 'Jean-Pierre', 'France');
INSERT INTO acteur VALUES(20, 'Copolla', 'Francis-Ford', 'Etats-Unis');
INSERT INTO acteur VALUES(21, 'Seigner', 'Mathilde', 'France');
INSERT INTO acteur VALUES(22, 'Seigner', 'Emmanuelle', 'France');
INSERT INTO acteur VALUES(23, 'Berri', 'Claude', 'France');
INSERT INTO acteur VALUES(24, 'Damiens', 'François', 'Belgique');
INSERT INTO acteur VALUES(25, 'Poelvoorde', 'Benoit', 'Belgique');
INSERT INTO realisateur VALUES(1, 'Hooper', 'Tom', 'Angleterre');
INSERT INTO realisateur VALUES(2, 'Copolla', 'Sofia', 'Etats-Unis');
INSERT INTO realisateur VALUES(3, 'Penn', 'Sean', 'Etats-Unis');
INSERT INTO realisateur VALUES(4, 'Nolan', 'Christopher', 'Etats-Unis');
INSERT INTO realisateur VALUES(5, 'Canet', 'Guillaume', 'France');
INSERT INTO realisateur VALUES(8, 'Dujardin', 'Jean', 'France');
INSERT INTO realisateur VALUES(9, 'Boon', 'Dany', 'France');
INSERT INTO realisateur VALUES(12, 'Pecas', 'Max', 'France');
INSERT INTO realisateur VALUES(13, 'Eastwood', 'Clint', 'Etats-Unis');
INSERT INTO realisateur VALUES(14, 'Boyle', 'Danny', 'Etats-Unis');
INSERT INTO realisateur VALUES(16, 'Scorcesse', 'Martin', 'Etats-Unis');
